### ISSUE TITLE
connect method 

### ISSUE THREAD

**Issue by sajankumar** [chrisenytc/ng-socket#4]
Can you tell me how to fix this ?

TypeError: Cannot call method 'connect' of undefined
    at Object.<anonymous> (http://localhost:8888/SPA_Application/server/js/ngSocket.js:17:23)
    at Object.d [as invoke](https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:33:335)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:35:77
    at c (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:33:83)
    at Object.d [as invoke](https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:33:300)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:35:77
    at c (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:33:83)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:33:300)
    at Object.instantiate (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:33:464)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:65:486 <div ng-view="" class="ng-scope">

**Comment by loadedsith** [comment]
With requirejs:

    //require.config.js
    shim:{
        'ng-socket': {
          deps: [
            'angular'
            './startSocketIo',
          ]
      }

    //startSocketIo.js
    define([
      'socket.io-client'],function(io) {
        'use strict';
        window.io = io;
      });
